services:
  sqlserver:
    build:
      context: .
      dockerfile: docker/live/Dockerfile
    image: mssql-dart-live:local
    container_name: mssql-dart-live
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-Strong_test_password_123!}"
    ports:
      - "14333:1433"
